### ISSUE TITLE
pydevconsole.py: error: unrecognized arguments: --mode=client

### ISSUE THREAD

**Issue by winsonfzyang** [krpouncy/PyMuse#2]
Hello,
I'm using Muse2 to set up a connection. I've set the IP on Muse Monitor to my computer IP address, and followed your guide to establish a connection

`
# Start the server
headband = PyMuse.Headband(ip = computerIP, port = 5000)
headband.start_server()
`

However, this problem came out:
usage: pydevconsole.py [-h] [--ip IP] [--port PORT]
pydevconsole.py: error: unrecognized arguments: --mode=client

I'm not sure what is causing this. Can you help?

Regards,
Winson

**Comment by krpouncy** [comment]
Sorry for the untimely response and inconvience. I have encountered this problem myself when making classes that inherrit from both PyMuse.Headband and QThread. A solution I have found is to set the IP and Port after you instantiate the headband. Please let me know if this way works for you. I'll look into fixing this issue.

```python
headband = PyMuse.Headband()
headband.setServerInfo(computerIP, 5000)
headband.start_server()
```
